version: "3.8"

services:
  db:
    container_name: mssql_react_crud1_container
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    hostname: db
    networks:
      - back_network
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Pa55w0rd!
      - MSSQL_SA_PASSWORD=Pa55w0rd!
      - MSSQL_PID=Express
    ports:
      - target: 1433
        published: 1433
        protocol: tcp
        mode: host
    volumes:
      - data_volume:/var/opt/mssql
  api:
    container_name: aspnet_react_crud1_container
    restart: always
    hostname: api
    image: aspnet_react_crud1_image
    networks:
      - back_network
      - front_network
    environment:
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=5001
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - target: 80
        published: 5000
        protocol: tcp
        mode: host
      - target: 443
        published: 5001
        protocol: tcp
        mode: host
    depends_on:
      - db
    volumes:
      - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/
    working_dir: /app
    stdin_open: true
    tty: true
    entrypoint: [
        './wait-for-it.sh',
        'db:1433',
        '-t',
        '190',
        '--',
        'dotnet',
        'ReactAspCoreCrud1.dll',
    ]
  client:
    container_name: client_react_crud1_container
    restart: always
    hostname: client
    image: client_react_crud1_image
    networks:
      - front_network
    environment:
      NODE_ENV: development
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
    depends_on:
      - api
    volumes:
      - ./react-aspcore-crud1:/app
      - node_modules:/app/node_modules
    
networks:
  back_network:
    driver: bridge
  front_network:
    driver: bridge
volumes:
  data_volume:
    driver: local
  node_modules:
    driver: local