FROM mcr.microsoft.com/dotnet/core/sdk:3.1.404-buster
WORKDIR /app

# Copy the csproj file and restore any dependencies (via nuget)
COPY *.sln ./
COPY *.csproj ./
RUN dotnet restore

ENTRYPOINT ["dotnet","watch","run","--no-launch-profile"]